import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
import React, { useEffect, useRef, useState } from 'react'
import { Canvas, useFrame } from '@react-three/fiber'
import { Edges, Stats, Text, useCursor, useTexture } from '@react-three/drei'
import { ethers } from 'ethers'
import { createClient } from 'urql'
import * as THREE from 'three'
import { useRoute } from 'wouter'
import useLocation from 'wouter/use-location'
import { easing } from 'maath'


const Home = () => {

  const GOLDENRATIO = 1.61803398875

  const [address, setAddress] = useState("");

  const [MutantTokens, setMutantTokens] = useState([]);
  const [BoredTokens, setBoredTokens] = useState([]);

  const MutantAPIURL = "https://api.thegraph.com/subgraphs/name/ibrahimsam96/boredandmutant-apes"
  const BoredAPIURL = "https://api.thegraph.com/subgraphs/name/gautamraju15/bayc-indexer"

  const Mutantquery = `
  {
    tokens(where: {owner_: {id: "${address}"}}) {
      tokenID
      imageURI
    }
  }
`
  const Boredquery = `
{
  boredApeTokens(where: {owner: "${address}"}) {
    tokenID
    imageURI
    owner {
      id
    }
  }
}
`
  const client = createClient({
    url: MutantAPIURL
  })
  const client2 = createClient({
    url: BoredAPIURL
  })

  useEffect(() => {
    let isAddress = ethers.utils.isAddress(address)
    if (isAddress) {
      fetchData()
    }
  }, [address])



  async function fetchData() {
    const mutantresponse = await client.query(Mutantquery, {}).toPromise();
    const boredresponse = await client2.query(Boredquery, {}).toPromise();

    console.log('mutantresponse:', mutantresponse)
    console.log('boredresponse:', boredresponse)

    // setTokens(response.data.tokens);
  }

  const Frame = ({ ...props }) => {

    const project = useRef()
    const frame = useRef();
    const [, params] = useRoute('/3D/:id')
    const [hovered, hover] = useState(false)
    const [location, setLocation] = useLocation()

    const isActive = params?.id === name;
    useCursor(hovered)


    const ImageMaterial = () => {
      const texture = useTexture(`\Textures/${name}.`)
      return (
        <meshBasicMaterial ref={project} map={texture} toneMapped={false} />
      )

    }


    return (
      <group {...props}>
        <mesh
          ref={project}
          name={name}
          onPointerOver={(e) => (e.stopPropagation(), hover(true))}
          onPointerOut={() => hover(false)}
          scale={[1.1, GOLDENRATIO, 0.05]}
          position={[0, GOLDENRATIO / 1.9, 0]}
        >
          <boxGeometry />
          <meshStandardMaterial color={"black"} metalness={0.5} roughness={0.5} envMapIntensity={2} />
          <mesh ref={frame} raycast={() => null} scale={[0.95, 0.93, 0.9]} position={[0, 0, 0.2]}>
            <boxGeometry />

            {/* <ImageMaterial /> */}

            <Edges
              scale={1.1}
              threshold={15} // Display edges only when the angle between two faces exceeds this value (default=15 degrees)
              color={isActive || hovered ? "orange" : "turquoise"}
            />
          </mesh>

          {/* <Image raycast={() => null} ref={project} position={[0, 0, 0.7]} url={url} /> */}
        </mesh>

        <Text color={"White"} maxWidth={0.1} anchorX="left" anchorY="top" position={[0.65, GOLDENRATIO, 0]} fontSize={0.05}>
          {name}
        </Text>
      </group>
    )
  }

  const Frames = ({ projects, q = new THREE.Quaternion(), p = new THREE.Vector3() }) => {
    const ref = useRef();
    const clicked = useRef();
    const [, params] = useRoute('/3D/:id')
    const [, setLocation] = useLocation()

    useFrame((state, delta) => {
      clicked.current = ref.current.getObjectByName(params?.id)
      // console.log(ref.current)
      if (clicked.current) {
        clicked.current.parent.updateWorldMatrix(true, true)
        clicked.current.parent.localToWorld(p.set(0, GOLDENRATIO / 1.9, 1.4))
        clicked.current.parent.getWorldQuaternion(q)
      }
      else {
        p.set(0, 0, 0)
        q.identity()
      }
    })

    // Selects object to ease, 
    // How fast camera moves after each project is selected
    useFrame((state, dt) => {
      easing.damp3(state.camera.position, p, 0.3, dt)
      easing.dampQ(state.camera.quaternion, q, 0.3, dt)

    })

    return (
      <React.Fragment>
        <group
          ref={ref}
          onClick={(e) => {
            e.stopPropagation(),
              setLocation(clicked.current == e.object ? '/3D' : '/3D/' + e.object.name)
          }}
          onPointerMissed={() => setLocation('/3D')}>
          {projects.map((props, index) => <Frame key={props.url} {...props} index={index} /> /* prettier-ignore */)}

        </group>
      </React.Fragment>
    )
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`h-full min-h-screen w-full grid grid-cols-[repeat(7,1fr)] grid-rows-[100px,25px,400px,100px] bg-[black]`}>
        <input
          placeholder='Search By Owner Address'
          className={` px-2 self-center justify-self-center col-start-1 col-end-8 bg-black hover:bg-[#353434] border-slate-500 border-[1px] rounded-sm focus:outline-none text-neutral-50 min-w-[300px]`}
          type="text"
          onChange={(e) => {
            setAddress(e.target.value)
          }}
        >
        </input>
        <Canvas className={`row-start-3 col-start-1 col-span-7`} shadows camera={{ fov: 70, position: [0, 2, 15] }}>
          <ambientLight intensity={1} />

          {/* <Frames projects={projects} /> */}

          <Stats />
        </Canvas>
      </div>
    </>
  )
}

export default Home;
